#!/usr/bin/env python3
# -*- mode: python -*-

import sys
import os
import urllib.request
from urllib.parse import urlparse

import yaml


def get_yaml_data(fname):
    with open(fname) as fp:
        fcontent = fp.read()

    return yaml.load(fcontent)


def get_source_urls(data):
    for source in data["Sources"]:
        yield make_url(source, data)


def make_url(url, data):
    for key, value in data.items():
        key_to_replace = "%{{{}}}".format(key.lower())
        if key_to_replace in url:
            url = url.replace(key_to_replace, value)
    return url


def save_source(url):
    fname = os.path.basename(urlparse(url).path)
    fpath = os.path.join(os.path.abspath("."), "SOURCES", fname)
    if os.path.exists(fpath):
        print("Already exists at {}".format(fpath))
        return

    content = download_url(url)
    os.makedirs(os.path.dirname(fpath), exist_ok=True)
    with open(fpath, "wb") as fp:
        fp.write(content)
    print("Saved as {}".format(fpath))


def download_url(url):
    print("Downloading {}".format(url))
    with urllib.request.urlopen(url) as fp:
        return fp.read()


def main(args):
    if len(args) != 2 or not args[1].endswith(".yaml"):
        print("Must give an yaml file as argument")
        return -1

    fname = args[1]
    data = get_yaml_data(fname)
    for url in get_source_urls(data):
        save_source(url)

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
