# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       physfs

# >> macros
# << macros

Summary:    Filesystem abstraction library
Version:    2.0.3
Release:    1
Group:      Development/Libraries
License:    zlib
URL:        https://icculus.org/physfs/
Source0:    https://icculus.org/%{name}/downloads/%{name}-%{version}.tar.bz2
Source100:  physfs.yaml
Requires:   zlib
BuildRequires:  pkgconfig(zlib)
BuildRequires:  cmake

%description
%{summary}.

%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for %{name}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake . 
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_libdir}/libphysfs.*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_bindir}/*
%{_includedir}/*
# >> files devel
# << files devel
