# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       stow

# >> macros
# << macros

Summary:    Symlink farm manager
Version:    2.2.2
Release:    1
Group:      Applications/File
License:    GPLv2+
URL:        https://www.gnu.org/software/stow/
Source0:    https://ftp.gnu.org/gnu/%{name}/%{name}-%{version}.tar.gz
Source100:  stow.yaml
Requires:   perl
BuildRequires:  perl

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/*
%{_datadir}/*
# >> files
# << files
